<h1 class="content-title">トラップタワー、レッドストーン回路の規模</h1>
<div style="padding-left: 1rem">
	各回路、トラップタワーで範囲、ピストン、レッドストーンパウダー、レッドストーンブロック、リピーター、コンパレーター、ディスペンサー、ドロッパー、レッドストーンランプの数を測定し、すべての条件が当てはまる最小の規模をその回路、トラップタワーの規模とします。<br> 値測定は<a class="hide-line" href="?category=plugins&content=worldedit">WorldEdit</a>の機能を使用し測定した値を使用します。<br>
</div>
<div style="height: 1rem"></div>
<table style="font-size: 1rem">
	<tr>
		<th>規模</th>
		<th>範囲</th>
		<th>ピストン数</th>
		<th>レッドストーンパウダー数</th>
		<th>レッドストーンブロック数</th>
		<th>リピーター数</th>
		<th>コンパレーター数</th>
		<th>ディスペンサー数</th>
		<th>ドロッパー数</th>
		<th>レッドストーンランプ数</th>
	</tr>
	<tr>
		<th>小規模</th>
		<td>16x16x16以内</td>
		<td>20個以内</td>
		<td>32個以内</td>
		<td>16個以内</td>
		<td>16個以内</td>
		<td>16個以内</td>
		<td>16個以内</td>
		<td>16個以内</td>
		<td>16個以内</td>
	</tr>
	<tr>
		<th>中規模</th>
		<td>32x32x32以内</td>
		<td>64個以内</td>
		<td>128個以内</td>
		<td>64個以内</td>
		<td>64個以内</td>
		<td>64個以内</td>
		<td>64個以内</td>
		<td>64個以内</td>
		<td>64個以内</td>
	</tr>
	<tr>
		<th>大規模</th>
		<td>64x64x64以内</td>
		<td>128個以内</td>
		<td>256個以内</td>
		<td>128個以内</td>
		<td>128個以内</td>
		<td>128個以内</td>
		<td>128個以内</td>
		<td>128個以内</td>
		<td>128個以内</td>
	</tr>
	<tr>
		<th>超大規模</th>
		<td>上記に当てはまらない物</td>
		<td>上記に当てはまらない物</td>
		<td>上記に当てはまらない物</td>
		<td>上記に当てはまらない物</td>
		<td>上記に当てはまらない物</td>
		<td>上記に当てはまらない物</td>
		<td>上記に当てはまらない物</td>
		<td>上記に当てはまらない物</td>
		<td>上記に当てはまらない物</td>
	</tr>
</table>